version: "3"

services:

  mongo:

    image: mongo:3.2.20

    restart: always

    container_name: mongo

    volumes:

      - ./mongod.conf:/etc/mongod.conf

    ports:

      - "27017:27017"

  app:

    container_name: app

    restart: always

    build: ./app

    ports:

      - "80:3000"

    links:

      - mongo

    environment:

      - DB_HOST=mongodb://mongo:27017/posts

    # command: node seeds/seed.js